CREATE TABLE "HR"."MEMBER" 
   (	
   	"ID" VARCHAR2(10), 
	"PW" VARCHAR2(10), 
	"NAME" VARCHAR2(10), 
	"TEL" VARCHAR2(10)
   ) 
   
CREATE TABLE "HR"."BBS"
(	
	"no" VARCHAR2(100),
	"TITLE" VARCHAR2(100),
	"CONTENT" VARCHAR2(100),
	"WRITER" VARCHAR2(100)
)

CREATE TABLE "HR"."PRODUCT"(
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE VARCHAR2(200),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)

-- 한줄복사는 컨트롤 + 알트 + 화살표 아래

-- 한줄삭제는 컨트롤 + D

-- 저장할 대상 : 엔티티 (회원정보, 게시판, 상품),엔티티간의 관계: 회원이 상품을 주문하다(주문정보)

-- 엔티티 + 관계==>테이블로 만들자

CREATE TABLE HR.ORDERLIST (
"no" VARCHAR2(100),
MEMBER_ID VARCHAR2(100),
PRODUCT_ID VARCHAR2(100),
TOTAL_COUNT VARCHAR2(100)

)


CREATE TABLE HR.DEPART(
ID VARCHAR2(100),
NAME VARCHAR2(100),
INSTRUCTOR VARCHAR2(100)

)

INSERT INTO HR.DEPART VALUES ('0001', '홍길동', 'park')

INSERT INTO HR.DEPART VALUES ('0002', '김길동', 'LEE')

INSERT INTO HR.DEPART VALUES ('0003', '최길동', 'CHOI')

SELECT * FROM HR.DEPART


CREATE TABLE HR.STUDENT(
ID VARCHAR2(100),
NAME VARCHAR2(100),
TEL VARCHAR2(100),
DEPART_ID VARCHAR2(100)
)

INSERT INTO HR.STUDENT VALUES ('1111', '홍길동', '010', '0001')

INSERT INTO HR.STUDENT VALUES ('2222', '김길동', '011', '0002')

SELECT * FROM HR.STUDENT 

CREATE TABLE HR.SUBJECT(
ID VARCHAR2(100),
TITLE VARCHAR2(100),
DEPART_ID VARCHAR2(100)
)

INSERT INTO HR.SUBJECT VALUES ('1111', 'TITLE1', '0001')

INSERT INTO HR.SUBJECT VALUES ('2222', 'TITEL2', '0002')

SELECT * FROM HR.SUBJECT


CREATE TABLE "HR"."BBS2" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 

CREATE TABLE "HR"."BBS3" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
) 

--PK 제약조건 추가
ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK PRIMARY KEY ("no")

--FK 제약조건 추가
ALTER TABLE HR.BBS3 
ADD CONSTRAINT FK_MEMBER33 FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);

CREATE TABLE HR.DEPART2(
ID VARCHAR2(100),
NAME VARCHAR2(100),
INSTRUCTOR VARCHAR2(100),
CONSTRAINT "DEPART_PK22" PRIMARY KEY ("ID")

)

CREATE TABLE HR.STUDENT2(
ID VARCHAR2(100),
NAME VARCHAR2(100),
TEL VARCHAR2(100),
DEPART_ID VARCHAR2(100)
)

ALTER TABLE HR.STUDENT2
ADD CONSTRAINT STUDENT2_PK PRIMARY KEY("ID")

ALTER TABLE HR.STUDENT2
ADD CONSTRAINT FK_STUDENT2 FOREIGN KEY(DEPART_ID)REFERENCES HR.DEPART2

CREATE TABLE HR.MEMBER22
AS SELECT* FROM HR."MEMBER"

INSERT INTO HR.MEMBER22 
VALUES('banana3','banana3','banana3','banana3',sysdate)

SELECT * FROM HR.MEMBER22

INSERT INTO HR.MEMBER22 
VALUES('banana4','banana4','banana4','banana4',sysdate,'apple')

INSERT INTO HR.BBS 
VALUES (HR.BBS_ID_SEQ.NEXTVAL,'happy','happyday','ice')

SELECT * FROM HR.BBS

CREATE SEQUENCE pd_id_seq 
INCREMENT BY 1
START WITH 1

CREATE TABLE product3 (
	id number(38, 0),
	name varchar2(100)
)

INSERT INTO product3 
VALUES (pd_id_seq.nextval, 'shoes')

SELECT * FROM product3

CREATE TABLE HR.ORDERLIST3(
ID NUMBER(38,0),
TITLE VARCHAR2(100),
PRICE NUMBER(38,0)
)

CREATE SEQUENCE OR_SEQ
INCREMENT BY 1
START WITH 1

INSERT INTO HR.ORDERLIST3 VALUES(OR_SEQ.NEXTVAL,'apple','1000')

INSERT INTO HR.ORDERLIST3 VALUES(OR_SEQ.NEXTVAL,'banana','2000')

INSERT INTO HR.ORDERLIST3 VALUES(OR_SEQ.NEXTVAL,'orange','3000')

SELECT * FROM HR.ORDERLIST3 

SELECT * FROM HR.ORDERLIST3
ORDER BY ID -- 오름차순

SELECT * FROM HR.ORDERLIST3
WHERE ID >=2 ORDER BY ID DESC -- 내림차순

CREATE TABLE HR.DEPT
(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE HR.EMP
(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE HR.SALGRADE
(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE HR.DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY
(DEPTNO));


ALTER TABLE HR.EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO));

 
ALTER TABLE HR.EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES HR.DEPT (DEPTNO));

SELECT * FROM HR.EMP -- SELECTION

SELECT DEPTNO FROM HR.EMP -- PROJECTION

SELECT DISTINCT DEPTNO FROM HR.EMP -- DISTINCT중복제거

SELECT ENAME,SAL * 12 AS YEARSAL FROM HR.EMP

SELECT * FROM HR.EMP ORDER BY SAL DESC

SELECT * FROM HR.EMP  
WHERE DEPTNO =30 ORDER BY EMPNO DESC

SELECT * FROM HR.EMP  
WHERE NOT DEPTNO =30 ORDER BY EMPNO DESC

SELECT * FROM HR.EMP  
WHERE DEPTNO =30 AND JOB = 'SELESMAN'

SELECT * FROM HR.EMP  
WHERE DEPTNO =30 OR JOB = 'SELESMAN'

SELECT * FROM HR.EMP WHERE sal >=3000

SELECT * FROM HR.EMP WHERE sal !=3000

SELECT * FROM HR.EMP  
WHERE job IN ('SELESMAN','MANAGER') ORDER BY JOB 

SELECT * FROM HR.EMP  
WHERE job NOT IN ('SELESMAN','MANAGER') ORDER BY JOB 

SELECT * FROM HR.EMP  
WHERE SAL BETWEEN 2000 AND 3000

SELECT * FROM HR.EMP  
WHERE SAL NOT BETWEEN 2000 AND 3000

SELECT *FROM HR.EMP
WHERE ENAME LIKE '_L%'

SELECT *FROM HR.EMP
WHERE ENAME NOT LIKE '_L%'

SELECT *FROM HR.EMP
WHERE COMM IS NULL 

SELECT *FROM HR.EMP
WHERE COMM IS NOT NULL


CREATE TABLE HR.DEPT_TEMP2
AS SELECT * FROM HR.DEPT

SELECT* FROM HR.DEPT_TEMP2

UPDATE HR.DEPT_TEMP2 
SET LOC='SEOUL'

UPDATE HR.DEPT_TEMP2 
SET DNAME = 'DATABASE', LOC ='BUSAN'
WHERE DEPTNO =40

DELETE FROM HR.DEPT_TEMP2
WHERE DNAME = 'SALES'

ALTER TABLE HR.PRODUCT MODIFY PRICE NUMBER(38,0)

SELECT * FROM HR.PRODUCT ORDER BY PRICE DESC 

SELECT NAME , CONTENT ,PRICE  FROM HR.PRODUCT ORDER BY COMPANY 

SELECT DISTINCT COMPANY FROM HR.PRODUCT

SELECT NAME,PRICE* 12 AS PRICE5 FROM HR.PRODUCT 

SELECT NAME, COMPANY FROM HR.PRODUCT  WHERE PRICE = 5000

SELECT NAME, PRICE, COMPANY FROM HR.PRODUCT WHERE PRICE BETWEEN 3000 AND 6000

SELECT COMPANY, NAME FROM HR.PRODUCT WHERE COMPANY != 'c100'

SELECT NAME,PRICE FROM HR.PRODUCT WHERE COMPANY = 'c100'OR COMPANY = 'c200'

SELECT * FROM HR.PRODUCT  WHERE NAME LIKE '%4'

SELECT * FROM HR.PRODUCT  WHERE CONTENT LIKE '%food%'

UPDATE HR.PRODUCT SET CONTENT ='품절' WHERE PRICE =5000

UPDATE HR.PRODUCT SET IMG ='o.png',PRICE ='10000' WHERE ID ='100'OR ID ='102'

SELECT * FROM HR.PRODUCT 

DELETE FROM HR.PRODUCT WHERE COMPANY ='c100'

DELETE FROM HR.PRODUCT














